default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: scavenger_hunt_development

test:
  <<: *default
  database: scavenger_hunt_test

production:
  <<: *default
  database: scavenger_hunt_production
  username: 
  password: 